### ISSUE TITLE
hud got cropped

### ISSUE THREAD

**Issue by xx-bear21** [marconsou/deep-dungeon-tracker#3]
hi i dont know what happen but the tracker hud got cropped

**Comment by marconsou** [comment]
Did you change the scale of the window? can you send a screenshot?

**Comment by xx-bear21** [comment]
![image_2023-03-22_160623352](https://user-images.githubusercontent.com/128273638/226838349-9ff329fb-e5e9-4e1c-9265-3d85874ae4e4.png)

**Comment by marconsou** [comment]
When you change the scale value of the window does it get cropped too?
I think if you edit your dalamudUI.ini and change the size of the window it might work.

```
[Window][Tracker##Deep Dungeon Tracker]
Pos=2173,1
Size=386,407
Collapsed=0

[Window][FloorSetTime##Deep Dungeon Tracker]
Pos=1897,1
Size=275,199
Collapsed=0

[Window][Score##Deep Dungeon Tracker]
Pos=1948,201
Size=224,54
Collapsed=0

[Window][Statistics##Deep Dungeon Tracker]
Pos=1188,435
Size=1359,989
Collapsed=0
```

**Comment by xx-bear21** [comment]
yeah, its still get cropped too if i change the value, already manually changing in the dalamudui.ini but still got cropped idk what happen

**Comment by marconsou** [comment]
Make sure you are editing the file with the game closed.
Can you send me your values from dalamudUI.ini so I can take a look and test myself?
Send me your DeepDungeonTracker.json config file too.
Are you using any feature thats affect the game resolution in anyway, like dynamic resolution or anything else? Try to change your resolution to another value and notice if the cropped area is exactly the same from the posted image.

**Comment by marconsou** [comment]
Ok, i think I figured out the problem:
![Image](https://user-images.githubusercontent.com/27457164/227451982-a4fbe930-2c3b-4c6e-8edb-b0ff270bfe25.png)
It's the dalamud font size settings (when I changed from 12pt to a value below, like 9.6pt i got it cropped)
What font size are you using? Can you test other font sizes?

**Comment by marconsou** [comment]
I've fixed this issue (but it will only be available on the next plugin release).
Can you confirm if changing the size of the font fix the issue?

**Comment by xx-bear21** [comment]
wtf?? wow it actually works when i change the 9.6 to 12, the bug is weird

**Comment by marconsou** [comment]
The version update (v0.4.0.0) is available, check if it will work now.
